import { Metadata } from "next";
import "@/styles/globals.css";
import { Toaster } from "@pheralb/toast";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white min-h-screen overflow-hidden relative">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
