import { Metadata } from "next";
import "@/styles/globals.css";
import { Toaster } from "@pheralb/toast";
import { Suspense } from "react";
import Loader from "@/components/Loader";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white min-h-screen max-h-screen overflow-hidden relative">
        <Suspense fallback={<Loader />}>
          {children}
          <Toaster />
        </Suspense>
      </body>
    </html>
  );
}
